<?php

use Sandesh\ReportIssue\Block\SaveForm;

/**
 * @var SaveForm $block
 */

?>

<div class="container">
    <div class="issue-details">
        <form action="<?= $block->getFormUrl() ?>" method="post">
            <div class="user-name">
                <label for="user_name">Username <span class="required">*</span> </label>
                <input type="text" name="user_name" id="username" value="" placeholder="" required>
            </div>
            <div class="user-phone">
                <label for="phone_number">Phone Number <span class="required">*</span> </label>
                <input type="tel" name="phone_number" id="phonenumber" minlength="10" maxlength="10" value=""
                       placeholder="" required>
            </div>
            <div class="user-email">
                <label for="email_id">Email-ID <span class="required">*</span> </label>
                <input type="email" name="email_id" id="email" value="" placeholder="" required>
            </div>
            <div class="issue-title">
                <label for="issue_title">Issue Title <span class="required">*</span> </label>
                <input type="text" name="issue_title" id="issuetitle" value="" placeholder="" required>
            </div>
            <div class="issue-description">
                <label for="issue_description">Issue Description <span class="required">*</span> </label>
                <textarea name="issue_description" id="description" cols="30" rows="10" required></textarea>
            </div>
            <div class="submit">
                <input class="submit" type="submit" value="Report">
            </div>
        </form>
    </div>
</div>
